version: 2.1

commands:
  verify-pre-run:
    steps:
      - checkout
      - attach_workspace:
          at: .

executors:
  docker-go-executor:
    docker:
      - image: cimg/go:1.18.2
    resource_class: small

jobs:
  install:
    executor: docker-go-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: make install
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  verify-go-mod:
    executor: docker-go-executor
    steps:
      - verify-pre-run
      - run: make verify-go-mod

  verify-git:
    executor: docker-go-executor
    steps:
      - verify-pre-run
      - run: make verify-git

  verify-go-build:
    executor: docker-go-executor
    steps:
      - verify-pre-run
      - run: make verify-build

  verify-linting:
    executor: docker-go-executor
    steps:
      - verify-pre-run
      - run: make verify-lint

  verify-unit-tests:
    executor: docker-go-executor
    parallelism: 5
    steps:
      - verify-pre-run
      - run: go test -v $(go list ./... | circleci tests split --split-by=timings)

workflows:
  integration:
    jobs:
      - install
      - verify-go-mod:
          requires: [install]
      - verify-git:
          requires: [install]
      - verify-go-build:
          requires: [install]
      - verify-linting:
          requires: [install]
      - verify-unit-tests:
          requires: [install]
