// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/config/describe": {
            "get": {
                "description": "WIP, describe current carbonaut configuration",
                "tags": [
                    "config"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/config/load": {
            "put": {
                "description": "WIP, update carbonaut configuration",
                "tags": [
                    "config"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/config/validate": {
            "post": {
                "description": "WIP, validate provided carbonaut configuration",
                "tags": [
                    "config"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/connector/connect/aws": {
            "post": {
                "description": "WIP, connect to aws data source",
                "tags": [
                    "connector"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/connector/connect/azure": {
            "post": {
                "description": "WIP, connect to azure data source",
                "tags": [
                    "connector"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/connector/connect/gcp": {
            "post": {
                "description": "WIP, connect to gcp data source",
                "tags": [
                    "connector"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/connector/connections": {
            "get": {
                "description": "WIP, list carbonaut data provider connections",
                "tags": [
                    "connector"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/data/export": {
            "get": {
                "description": "Export carbonaut data",
                "tags": [
                    "data"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/data/import/csv": {
            "post": {
                "description": "Import data in a csv file to carbonaut",
                "consumes": [
                    "text/plain"
                ],
                "tags": [
                    "data"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Used to match provided data format to provider",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/data/import/raw": {
            "post": {
                "description": "Import raw bytes of provider data to carbonaut",
                "consumes": [
                    "text/plain"
                ],
                "tags": [
                    "data"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Used to match provided data format to provider",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/data/storage": {
            "get": {
                "description": "Describe carbonaut storage connection",
                "tags": [
                    "data"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Configure a connection to storage",
                "tags": [
                    "data"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/init": {
            "post": {
                "description": "Initialize carbonaut to be fully functional",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/status/": {
            "get": {
                "description": "Carbonaut Status Endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Carbonaut API",
	Description:      "This API is used to interact with Carbonaut resources",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
