# This is a basic workflow to help you get started with Actions

name: verify

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.0'
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        make install

    # Run build of the application
    - name: Verify
      run: make verify
